### ISSUE TITLE
Build tool straight out doesn't work

### ISSUE THREAD

**Issue by justrhysism** [zingchart/ZingChart#2]
Incorrect file references, incorrect file names, it looks as though it hasn't been touched for a long while, but has been shuffled around somewhat.

**Comment by mike-schultz** [comment]
Hi there,

Thanks for bringing this to our attention. I've gone ahead and fixed the paths issue on the develop branch : https://github.com/zingchart/ZingChart/tree/develop. It will be merged into master on our next iteration. 

We also have an online version of the builder for your convenience as well : http://www.zingchart.com/docs/build-generator/

**Comment by mike-schultz** [comment]
@justrhysism
