### ISSUE TITLE
Unable to disable context menu

### ISSUE THREAD

**Issue by justrhysism** [zingchart/ZingChart#3]
The [docs state](http://www.zingchart.com/docs/json-attributes-syntax/gui-objects/context-menu/) that the context menu can be disabled by setting:

```JSON
"gui": {
    "context-menu": {
        "visible": false
    }
}
```

However I am unable to get this to work.

**Comment by mike-schultz** [comment]
Hi, we actually have fixed this issue and it will be is in our next build. The new build should be coming out very shortly. 
One thing to note about the visible option is it can only be used by users with a license file (docs are being updated to reflect that). Users without a license file can reduce the context menu to just the "About ZingChart"  item by setting the property `"empty" : false.`

**Comment by justrhysism** [comment]
I figured that it would be the case regarding the licence file - would be good for the docs to make that clear, otherwise it does feel broken.
