### ISSUE TITLE
Word Cloud has issues when the chart is redrawn

### ISSUE THREAD

**Issue by ccoley** [zingchart/ZingChart#4]
Anytime the word cloud chart is redrawn without reloading the page the old cloud of text remains and the new cloud of text is drawn over top of it. I have a live example you can look at [here][1] and the source code for that page is located in [this repo][2].

This redraw happens anytime you resize the viewport, which includes zooming on desktop browsers and orientation changes in mobile browsers. 

This issue seems to only occur when using the `fullscreen: true` rendering option.

Here is a before image:
![wordclouds](https://cloud.githubusercontent.com/assets/1178579/8708706/7c2640d2-2af2-11e5-8e79-25bf99f0de1a.png)

and an after image:
![after](https://cloud.githubusercontent.com/assets/1178579/8708720/8b93681a-2af2-11e5-95db-7985bf3a36c8.png)

[1]: http://local.codingallnight.com:8080/pint/word-cloud.html
[2]: https://github.com/ccoley/pint/blob/master/word-cloud.html

**Comment by mike-schultz** [comment]
Looks like an issue! We'll get on fixing that right away.

**Comment by mike-schultz** [comment]
Fixed in 2.1.3
