### ISSUE TITLE
Still no main entry in bower.json

### ISSUE THREAD

**Issue by bsitruk** [zingchart/ZingChart#6]
The main entry in bower.json has recently been add.
However, when I get zingchart from "bower install zingchart", the main entry is still missing.

Do you know why ?

**Comment by mike-schultz** [comment]
Hi there, 
I did the pull request into master, but it won't be available on bower until we tag a release on github. We're preparing a new build to release right now and it should be available within the next week or two.

**Comment by bsitruk** [comment]
Thanks !
