### ISSUE TITLE
highlight-lengend purpose

### ISSUE THREAD

**Issue by bsitruk** [zingchart/ZingChart#7]
Hello,
What is the purpose of the new "highlight-legend" property ?

**Comment by mike-schultz** [comment]
Hi, 
The highlight-legend property allows legend items to be more visible during mousing over specific series elements. Example : http://demos.zingchart.com/view/E0HUB4DU . In the future, please direct all general questions to `support@zingchart.com` , or using our general chat located on our website @ www.zingchart.com
