### ISSUE TITLE
CDN versioning broken?

### ISSUE THREAD

**Issue by saintkepha** [zingchart/ZingChart#8]
Hi ZC team, not sure if this is the best place to report this issue but we noticed today that the CDN request to zingchart-treemap-min.js?v2.2.0 was returning build 2.2.1 (which seemed broken). 

Not sure if it's only the treemap component or others are affected as well.

**Comment by mike-schultz** [comment]
Hi @saintkepha , we are in the process of pushing to the newest build (v2.2.1) and as a result the cdn has the newest version. The github, npm, and bower repos will be updated as well today.

**Comment by saintkepha** [comment]
Hi @mike-shultz

I am using zingcharts via npm (v2.2.0).  Looks like some of the "extra" charts defaulted to using https://cdn.zingchart.com/modules but would've expected that the CDN way would've also retrieved the v2.2.0 component and not the v2.2.1 component.  I saw that the CDN request was tagged with ?v2.2.0 but the response was a v2.2.1 build instead.

**Comment by mike-schultz** [comment]
Ah yes, you are correct. Prior the build distributed were pulling modules in from the newest cdn modules folder, but going forward we will be setting it explicitly in our `index.js` that npm utilizes. I should be pushing out the new release within the hour to npm.
