### ISSUE TITLE
Cross hair not displaying

### ISSUE THREAD

**Issue by kcdipesh** [zingchart/ZingChart#9]
Crosshair (both Crosshair-x and Crosshair-y ) doesn't work for some chrome browsers*. (including the one in the demo at zingchart.com)
This problem is seen on chrome version  46 and 47 on windows.
It works on my latest chrome  47.0.2526.73 (64-bit) on ubuntu.

**Comment by mike-schultz** [comment]
Hi, this is a known bug in our current build of ZingChart v2.2.1 and it affects Windows users running touch screens. I believe our support team has contacted you since you have emailed us through support@zingchart.com and will be in touch with any future updates. We plan on fixing this issue soon.
